version: "3.8"

volumes:
  db-store:

services:
  # PHP
  app:
    container_name: app2_php
    build: ./infra/php
    volumes:
      - ./backend:/work
  # nginx
  web:
    image: nginx:1.18-alpine # nginxは1.10, 1.12 等の偶数が安定バージョン
    container_name: app2_nginx
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # MySQL
  db:
    container_name: app2_db
    build: ./infra/mysql
    ports:
      - 4306:3306 # Sequel Aceを使用する際
    volumes:
      - db-store:/var/lib/mysql
