version: "3.8"

volumes:
  db-store:

services:
  # PHP
  app:
    container_name: app2_php
    build: ./infra/php
    volumes:
      - ./backend:/work
  # nginx
  web:
    container_name: app2_nginx
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  # MySQL
  db:
    container_name: app2_db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: m_user
      MYSQL_PASSWORD: m_user
      TZ: 'Asia/Tokyo'
    volumes:
      - db-store:/var/lib/mysql
  # phpMyAdmin
  phpmyadmin:
    container_name: app2_pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
